version: '3'
services:
  web:
    image: python:3.9-slim
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    command: ["python", "-m", "http.server", "8000"]